---

- hosts: remove_node
  name: Scale-down role-based playbook
  become: yes

  roles:
    - scale_down

- hosts: all

  tasks:

  - name: Remove the node from all unicast files
    lineinfile:
      path: "{{os_conf_dir}}/unicast_hosts.txt"
      regexp: '{{ hostvars[item].ansible_private_host }}'
      state: absent
      backup: yes
    with_items: "{{ groups['remove_node'] }}"
    become: yes

  - name: Update Hosts | Remove hosts from inventory
    become_user: root
    become: yes
    lineinfile:
      path: /etc/hosts
      regexp: "{{ hostvars[item]['ansible_private_host'] }}"
      state: absent
      backup: yes
    with_items: "{{ groups['remove_node'] }}"

- hosts: jump_host
  name: configure nginx Custom role-based tasks for scale up
  become: yes

  roles:
    - role: custom_scaledown_role
      is_sf_cloud: is_sf_cloud