---
- include_tasks:
    file: pre-install.yml
    apply:
      tags:
        - install
        - upgrade
  tags:
    - install
    - upgrade
  when: install_sfagent | default(False)

- include_tasks:
    file: check_jcmd.yml
    apply:
      tags:
        - install
        - upgrade
  tags:
    - install
    - upgrade
  when: install_sfagent | default(False)

- include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - install
  when: install_sfagent | default(False)

- include_tasks:
    file: extra-vars.yml
    apply:
      tags:
        - install
        - upgrade
  tags:
    - install
    - upgrade
    - never
  ignore_errors: true
  when: env_vars is defined or include_paths is defined and install_sfagent | default(False)

- include_tasks:
    file: upgrade.yml
    apply:
      tags:
        - upgrade
  tags:
    - upgrade
    - never
  when: install_sfagent | default(False)

- include_tasks:
    file: validate.yml
    apply:
      tags:
        - install
        - upgrade
  tags:
    - install
    - upgrade
  when: install_sfagent | default(False)

- include_tasks:
    file: uninstall.yml
    apply:
      tags:
        - uninstall
  tags:
    - uninstall
    - never
  when: install_sfagent | default(False)

- include_tasks:
    file: help.yml
    apply:
      tags:
        - help
  tags:
    - help
    - never
  when: install_sfagent | default(False)

- include_tasks:
    file: generate-config.yml
    apply:
      tags:
        - generate-config
  tags:
    - generate-config
    - never
  when: install_sfagent | default(False)

- include_tasks:
    file: update-config.yml
    apply:
      tags:
        - update-config
  tags:
    - update-config
    - never
  when: install_sfagent | default(False)

- include_tasks:
    file: copy-config-sfagent.yml
    apply:
      tags:
        - copy-config-sfagent
  tags:
    - copy-config-sfagent
  when: install_sfagent | default(False)

- include_tasks:
    file: config_nginx.yml
    apply:
      tags:
        - config_nginx
  tags:
    - config_nginx
  when: configure_nginx | default(False) and is_sf_cloud | default(False)

- include_tasks:
    file: populate_jump_host.yml
    apply:
      tags:
        - populate_jump_host
  tags:
    - populate_jump_host
  when: is_sf_cloud | default(False)
