- name: Add is_sf_cloud flag in group vars
    become: true
    lineinfile:
      path: /usr/local/scaling_manager_lib/ansible_scripts/group_vars/all/all.yml
      regexp: "jump_host_bool: .*"
      line: "jump_host_bool: True"
      backup: true
      create: true
- name: Add jump_host_ip in group vars
  become: true
  lineinfile:
    path: /usr/local/scaling_manager_lib/ansible_scripts/group_vars/all/all.yml
    regexp: "jump_host_ip: .*"
    line: "jump_host_ip: {{ jump_host_ip }}"
    backup: true
    create: true
- name: Add jump_host_user in group vars
  become: true
  lineinfile:
    path: /usr/local/scaling_manager_lib/ansible_scripts/group_vars/all/all.yml
    regexp: "jump_host_user: .*"
    line: "jump_host_user: {{ jump_host_user | default('ubuntu') }}"
    backup: true
    create: true