---
- name: Get the present configmap
  become: true
  shell: kubectl get cm esnginx-sfnginxv1 -o yaml > /tmp/esnginx-sfnginxv1_cm.yaml
- name: Check if the excluding node ip is already present
  become: true
  shell: sed -n "/server {{ exclude_node_ip }}:9200;/p" /tmp/esnginx-sfnginxv1_cm.yaml
  register: check_node_ip
- name: Remove the node ip from configmap
  become: true
  lineinfile:
    path: /tmp/esnginx-sfnginxv1_cm.yaml
    regexp: server {{ exclude_node_ip }}:9200;
    state: absent
    backup: true
  when: check_node_ip.stdout != ""
- name: Apply the update config map
  become: true
  shell: kubectl apply -f /tmp/esnginx-sfnginxv1_cm.yaml
  when: check_node_ip.stdout != ""