---
- name: Get the present configmap
  become: true
  shell: kubectl get cm esnginx-sfnginxv1 -o yaml > /tmp/esnginx-sfnginxv1_cm.yaml
  ignore_errors: True
  register: kubectl_cmd
- debug: msg="Kubectl command execution failed. Please remove the node ip {{ exclude_node_ip }} manaully in nginx configmap. For more details please check troubleshooting guide."
  when: kubectl_cmd.stderr != ""
- name: Check if the excluding node ip is already present
  become: true
  shell: sed -n "/server {{ exclude_node_ip }}:9200;/p" /tmp/esnginx-sfnginxv1_cm.yaml
  register: check_node_ip
  when: kubectl_cmd.stderr == ""
- name: Remove the node ip from configmap
  become: true
  lineinfile:
    path: /tmp/esnginx-sfnginxv1_cm.yaml
    regexp: server {{ exclude_node_ip }}:9200;
    state: absent
    backup: true
  when: kubectl_cmd.stderr == "" and check_node_ip.stdout != ""
- name: Apply the update config map
  become: true
  shell: kubectl apply -f /tmp/esnginx-sfnginxv1_cm.yaml
  when: kubectl_cmd.stderr == "" and check_node_ip.stdout != ""