---

os_nodes: |-
        {% for item in groups['current_nodes'] -%}
          {{ hostvars[item]['ansible_private_host'] }}{% if not loop.last %}","{% endif %}
        {%- endfor %}","{% for item in groups['new_node'] -%}
          {{ hostvars[item]['ansible_private_host'] }}{% if not loop.last %}","{% endif %}
        {%- endfor %}
os_master_nodes: |-
        {% for item in groups['current_nodes'] -%}
        {% if hostvars[item]['roles'] == "master,data,ingest" %} {{ hostvars[item]['ansible_private_host'] }}","{% endif %}
        {%- endfor %}

## Common opensearch configuration parameters ##

# opensearch download
os_download_url: https://artifacts.opensearch.org/releases/bundle/opensearch

# Cluster type whether its single node or multi-node
cluster_type: multi-node

# Xmx represents the maximum size of total heap space
xms_value: "{{ RAMGB | int }}"
xmx_value: "{{ RAMGB | int }}"

os_conf_dir: "{{ os_home }}/config"
os_plugin_bin_path: "{{ os_home }}/bin/opensearch-plugin"
os_sec_plugin_conf_path: "{{ os_home + '/config/opensearch-security' if os_version is version('2.0.0', operator='>=', strict=True) else os_home + '/plugins/opensearch-security/securityconfig' }}"
os_sec_plugin_tools_path: "{{ os_home }}/plugins/opensearch-security/tools"
os_api_port: 9200

systemctl_path: /etc/systemd/system
