# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: OpenSearch Scaling Manager CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make build

    - name: Pack
      run: make pack
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scale-manager-artifacts
        path: |
          install_scaling_manager.yaml
          scaling_manager.tar.gz
          GNUmakefile
        retention-days: 1
